# **Roller Coaster Database**
<div style="text-align: center;">
  <img src="../assets/flipflap.jpg" width="30%" />
</div>

In [1]:
# Import and setup libraries
import pandas as pd
import numpy as np

# default options for pandas rows and cols
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

# plotting style
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [2]:
df = pd.read_csv("data/coaster_db.csv")

## EDA

### 1. Estructira general del dataset

In [5]:
# ¿Cuál es la forma (shape) del dataset?
df.shape

(1087, 56)

In [7]:
# ¿Cuáles son las primeras 5 filas del dataset?
df.head(5)

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,Height,Inversions,Lift/launch system,Cost,Trains,Park section,Duration,Capacity,G-force,Designer,Max vertical angle,Drop,Soft opening date,Fast Lane available,Replaced,Track layout,Fastrack available,Soft opening date.1,Closing date,Opened,Replaced by,Website,Flash Pass Available,Must transfer from wheelchair,Theme,Single rider line available,Restraint Style,Flash Pass available,Acceleration,Restraints,Name,year_introduced,latitude,longitude,Type_Main,opening_date_clean,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,600 ft (180 m),6 mph (9.7 km/h),Coney Island,Removed,"June 16, 1884",Wood,LaMarcus Adna Thompson,NaN,Lift Packed,50 ft (15 m),NaN,gravity,NaN,NaN,Coney Island Cyclone Site,1:00,1600 riders per hour,2.9,LaMarcus Adna Thompson,30°,43 ft (13 m),NaN,NaN,NaN,Gravity pulled coaster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1884,40.5740,-73.9780,Wood,1884-06-16,6 mph,9.7 km/h,6.0,mph,6.0,50.0,ft,NaN,0,2.9
1,Flip Flap Railway,NaN,NaN,Sea Lion Park,Removed,1895,Wood,Lina Beecher,NaN,NaN,NaN,1.0,NaN,NaN,a single car. Riders are arranged 1 across in ...,NaN,NaN,NaN,12,Lina Beecher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1895,40.5780,-73.9790,Wood,1895-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1896,41.5800,-81.5700,Other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,NaN,1.0,NaN,NaN,a single car. Riders are arranged 2 across in ...,NaN,NaN,NaN,NaN,Edward A. Green,NaN,NaN,NaN,NaN,Switchback Railway,NaN,NaN,NaN,1910,NaN,Giant Racer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901,40.5745,-73.9780,Steel,1901-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Edward A. Green,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901,39.3538,-74.4342,Steel,1901-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN

In [11]:
# ¿Cuáles son los nombres de las columnas?
df.columns  # equiv: df.axes[1]

Index(['coaster_name', 'Length', 'Speed', 'Location', 'Status', 'Opening date',
       'Type', 'Manufacturer', 'Height restriction', 'Model', 'Height',
       'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       'Track layout', 'Fastrack available', 'Soft opening date.1',
       'Closing date', 'Opened', 'Replaced by', 'Website',
       'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       'Single rider line available', 'Restraint Style',
       'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph', 'height_value', 'height_unit', 'height_ft',
       'Inversions_clean', 'Gforce_clean'],
      dtype='object')

In [18]:
# ¿Cuáles son los tipos de datos de cada columna?
# type(df.dtypes)  # pd.Series
df.dtypes

coaster_name                      object
Length                            object
Speed                             object
Location                          object
Status                            object
Opening date                      object
Type                              object
Manufacturer                      object
Height restriction                object
Model                             object
Height                            object
Inversions                       float64
Lift/launch system                object
Cost                              object
Trains                            object
Park section                      object
Duration                          object
Capacity                          object
G-force                           object
Designer                          object
Max vertical angle                object
Drop                              object
Soft opening date                 object
Fast Lane available               object
Replaced                          object
Track layout                      object
Fastrack available                object
Soft opening date.1               object
Closing date                      object
Opened                            object
Replaced by                       object
Website                           object
Flash Pass Available              object
Must transfer from wheelchair     object
Theme                             object
Single rider line available       object
Restraint Style                   object
Flash Pass available              object
Acceleration                      object
Restraints                        object
Name                              object
year_introduced                    int64
latitude                         float64
longitude                        float64
Type_Main                         object
opening_date_clean                object
speed1                            object
speed2                            object
speed1_value                     float64
speed1_unit                       object
speed_mph                        float64
height_value                     float64
height_unit                       object
height_ft                        float64
Inversions_clean                   int64
Gforce_clean                     float64
dtype: object

In [21]:
df.dtypes.value_counts()

object     46
float64     8
int64       2
Name: count, dtype: int64

In [36]:
# ¿Qué columnas contienen valores nulos y cuántos?
print('total cols with null values: ', df.isnull().any().sum())
print()
print('Columns with null values: \n', df.isnull().any().axes[0])
print()
print('NaN values per col: \n', df.isnull().sum())

total cols with null values:  50

Columns with null values:
 Index(['coaster_name', 'Length', 'Speed', 'Location', 'Status', 'Opening date',
       'Type', 'Manufacturer', 'Height restriction', 'Model', 'Height',
       'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       'Track layout', 'Fastrack available', 'Soft opening date.1',
       'Closing date', 'Opened', 'Replaced by', 'Website',
       'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       'Single rider line available', 'Restraint Style',
       'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph', 'height_value', 'height_unit', 'height_ft',
       'Inversions_clean', 'Gforce_clean'],
      dtype='object')

NaN values per col:
 coaster_name                        0
Length                            134
Speed                             150
Location                            0
Status                            213
Opening date                      250
Type                                0
Manufacturer                       59
Height restriction                256
Model                             343
Height                            122
Inversions                        155
Lift/launch system                292
Cost                              705
Trains                            369
Park section                      600
Duration                          322
Capacity                          512
G-force                           725
Designer                          509
Max vertical angle                730
Drop                              593
Soft opening date                 991
Fast Lane available              1018
Replaced                          914
Track layout                      752
Fastrack available               1068
Soft opening date.1               991
Closing date                      851
Opened                           1060
Replaced by                       999
Website                          1000
Flash Pass Available             1037
Must transfer from wheelchair     981
Theme                            1043
Single rider line available      1006
Restraint Style                  1065
Flash Pass available             1041
Acceleration                     1027
Restraints                       1063
Name                             1052
year_introduced                     0
latitude                          275
longitude                         275
Type_Main                           0
opening_date_clean                250
speed1                            150
speed2                            152
speed1_value                      150
speed1_unit                       150
speed_mph                         150
height_value                      122
height_unit                       122
height_ft                         916
Inversions_clean                    0
Gforce_clean                      725
dtype: int64

In [49]:
# ¿Existen filas o columnas completamente vacías?
print('Columns with more than 75% of null values: ')
percent_of_nulls = 100 * df.isnull().mean().round(4)
print(percent_of_nulls[percent_of_nulls > 75])

Columns with more than 75% of null values:
Soft opening date                91.17
Fast Lane available              93.65
Replaced                         84.08
Fastrack available               98.25
Soft opening date.1              91.17
Closing date                     78.29
Opened                           97.52
Replaced by                      91.90
Website                          92.00
Flash Pass Available             95.40
Must transfer from wheelchair    90.25
Theme                            95.95
Single rider line available      92.55
Restraint Style                  97.98
Flash Pass available             95.77
Acceleration                     94.48
Restraints                       97.79
Name                             96.78
height_ft                        84.27
dtype: float64

#### Calidad de datos

In [55]:
# ¿Hay filas duplicadas? ¿Cuántas?
# df.duplicated().any()
print('Total of duplicates rows: ', df.duplicated().sum())

Total of duplicates rows:  0

In [61]:
# ¿Qué columnas tienen valores nulos y en qué proporción?
null_percent_per_col = 100 * df.isnull().mean().round(2)
print('cols with null values: ')
print(null_percent_per_col[null_percent_per_col > 0])

cols with null values:
Length                           12.0
Speed                            14.0
Status                           20.0
Opening date                     23.0
Manufacturer                      5.0
Height restriction               24.0
Model                            32.0
Height                           11.0
Inversions                       14.0
Lift/launch system               27.0
Cost                             65.0
Trains                           34.0
Park section                     55.0
Duration                         30.0
Capacity                         47.0
G-force                          67.0
Designer                         47.0
Max vertical angle               67.0
Drop                             55.0
Soft opening date                91.0
Fast Lane available              94.0
Replaced                         84.0
Track layout                     69.0
Fastrack available               98.0
Soft opening date.1              91.0
Closing date                     78.0
Opened                           98.0
Replaced by                      92.0
Website                          92.0
Flash Pass Available             95.0
Must transfer from wheelchair    90.0
Theme                            96.0
Single rider line available      93.0
Restraint Style                  98.0
Flash Pass available             96.0
Acceleration                     94.0
Restraints                       98.0
Name                             97.0
latitude                         25.0
longitude                        25.0
opening_date_clean               23.0
speed1                           14.0
speed2                           14.0
speed1_value                     14.0
speed1_unit                      14.0
speed_mph                        14.0
height_value                     11.0
height_unit                      11.0
height_ft                        84.0
Gforce_clean                     67.0
dtype: float64

In [76]:
most_null_cols = percent_of_nulls[percent_of_nulls > 75].sort_values(ascending=False).index
most_null_cols

Index(['Fastrack available', 'Restraint Style', 'Restraints', 'Opened', 'Name',
       'Theme', 'Flash Pass available', 'Flash Pass Available', 'Acceleration',
       'Fast Lane available', 'Single rider line available', 'Website',
       'Replaced by', 'Soft opening date.1', 'Soft opening date',
       'Must transfer from wheelchair', 'height_ft', 'Replaced',
       'Closing date'],
      dtype='object')

In [83]:
# ¿Se pueden imputar, eliminar o transformar esos valores?
most_nulls_df = df[most_null_cols]

In [84]:
most_nulls_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1087 entries, 0 to 1086
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Fastrack available             19 non-null     object
 1   Restraint Style                22 non-null     object
 2   Restraints                     24 non-null     object
 3   Opened                         27 non-null     object
 4   Name                           35 non-null     object
 5   Theme                          44 non-null     object
 6   Flash Pass available           46 non-null     object
 7   Flash Pass Available           50 non-null     object
 8   Acceleration                   60 non-null     object
 9   Fast Lane available            69 non-null     object
 10  Single rider line available    81 non-null     object
 11  Website                        87 non-null     object
 12  Replaced by                    88 non-null     object
 13  Soft opening date.1            96 non-null     object
 14  Soft opening date              96 non-null     object
 15  Must transfer from wheelchair  106 non-null    object
 16  height_ft                      171 non-null    float64
 17  Replaced                       173 non-null    object
 18  Closing date                   236 non-null    object
dtypes: float64(1), object(18)
memory usage: 161.5+ KB

In [94]:
def nans(df: pd.DataFrame): return df[df.isnull().any(axis=1)]
def Nonans(df: pd.DataFrame): return df[df.notnull().any(axis=1)]

In [103]:
# ¿Qué columnas tienen datos inconsistentes o atípicos (e.g., alturas negativas)?
df.columns

Index(['coaster_name', 'Length', 'Speed', 'Location', 'Status', 'Opening date',
       'Type', 'Manufacturer', 'Height restriction', 'Model', 'Height',
       'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       'Track layout', 'Fastrack available', 'Soft opening date.1',
       'Closing date', 'Opened', 'Replaced by', 'Website',
       'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       'Single rider line available', 'Restraint Style',
       'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph', 'height_value', 'height_unit', 'height_ft',
       'Inversions_clean', 'Gforce_clean'],
      dtype='object')

In [121]:
df[['Length', 'Speed', 'Height', 'Cost', 'G-force', 'year_introduced', 'Acceleration']]

,Length,Speed,Height,Cost,G-force,year_introduced,Acceleration
0,600 ft (180 m),6 mph (9.7 km/h),50 ft (15 m),NaN,2.9,1884,NaN
1,NaN,NaN,NaN,NaN,12,1895,NaN
2,NaN,NaN,NaN,NaN,NaN,1896,NaN
3,NaN,NaN,NaN,NaN,NaN,1901,NaN
4,NaN,NaN,NaN,NaN,NaN,1901,NaN
...,...,...,...,...,...,...,...
1082,"3,444 ft (1,050 m)",53 mph (85 km/h),111 ft (34 m),NaN,4.7,2022,NaN
1083,"3,328 ft (1,014 m)",73 mph (117 km/h),178 ft (54 m),NaN,NaN,2022,NaN
1084,"3,169.3 ft (966.0 m)",59.3[1] mph (95.4 km/h),78.1 ft (23.8 m),NaN,4,2022,NaN
1085,770 ft (230 m),34 mph (55 km/h),112 ft (34 m),NaN,NaN,2022,NaN
1086,"3,300 ft (1,000 m)",58 mph (93 km/h),131 ft (40 m),NaN,NaN,2022,NaN

#### Resumen estadístico

#### Exploración de variables categóricas

In [ ]:
# ¿Cuáles son las categorías únicas en columnas como Type, Material Type, Status, Seating Type o Location?

#### Análisis greográfico